name: okepoint
description: Share location.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependency_overrides: 
  location_platform_interface: 3.0.0
  
dependencies:
  flutter:
    sdk: flutter


  # firebase services
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_remote_config: ^4.2.4
  cloud_firestore: ^4.8.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0

  # state managers
  flutter_riverpod: ^2.3.6 # https://pub.dev/packages/flutter_riverpod

  # navigation
  go_router: ^9.0.3 # https://pub.dev/packages/go_router

  # UI
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^3.0.0-pre


  # local storage
  shared_preferences: ^2.2.0

  # map
  google_maps_flutter: ^2.3.1
  flutter_polyline_points: ^1.0.0 # https://pub.dev/packages/flutter_polyline_points
  geolocator: ^9.0.2 # https://pub.dev/packages/geolocator


  # utils
  intl: ^0.17.0
  http: ^0.13.1
  random_string: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
